rootUrl: http://localhost.com:3000/
sessionsPerBrowser: 1

browsers:
    MainDesktop:
        rootUrl: http://localhost.com:3000/
        screenshotsDir: './gemini-screens/desktop'
        windowSize: 1900x1080
        desiredCapabilities:
            browserName: phantomjs

    MainMobile:
        rootUrl: http://localhost.com:3000/
        screenshotsDir: './gemini-screens/mobile'
        windowSize: 600x1056
        desiredCapabilities:
            browserName: phantomjs
