'use strict';

const languages = {
    'en-US': {
        'ID': 'ID',
        'Actions': 'Actions',
        'Hide': 'Hide',
        'Show the edition': 'Show the edition',
        'Show all %d Editions': 'Show all %d Editions',
        'by %s': 'by %s',
        'Account Settings': 'Account Settings',
        'FAQ': 'FAQ',
        'Terms of Service': 'Terms of Service',
        'Log out': 'Log out',
        'Previous': 'Previous',
        'Next': 'Next',
        '%s license': '%s license',
        'Log into': 'Log into',
        'Email': 'Email',
        'Enter your email': 'Enter your email',
        'Password': 'Password',
        'Enter your password': 'Enter your password',
        'Not an ascribe user': 'Not an ascribe user',
        'Sign up': 'Sign up',
        'Forgot my password': 'Forgot my password',
        'Rescue me': 'Rescue me',
        'LOGIN': 'LOGIN',
        'SIGNUP': 'SIGNUP',
        'Welcome to': 'Welcome to',
        'Sign up to ascribe': 'Sign up to ascribe',
        'Enter your password once again': 'Enter your password once again',
        'Enter a promocode here (Optional)': 'Enter a promocode here (Optional)',
        'I agree to the': 'I agree to the',
        'Confirm Password': 'Confirm Password',
        'Promocode': 'Promocode',
        'Sign up successful': 'Sign up successful',
        'We sent an email to your address': 'We sent an email to your address',
        'please confirm': 'please confirm',
        'Your password must be at least 10 characters': 'Your password must be at least 10 characters',
        'This password is securing your digital property like a bank account': 'This password is securing your digital property like a bank account',
        'Store it in a safe place': 'Store it in a safe place',
        'Reset the password for': 'Reset the password for',
        'Reset your ascribe password': 'Reset your ascribe password',
        'An email has been sent to': 'An email has been sent to',
        'Request successfully sent, check your email': 'Request successfully sent, check your email',
        'Reset your password': 'Reset your password',
        'Enter your email and we\'ll send a link': 'Enter your email and we\'ll send a link',
        'password successfully updated': 'password successfully updated',
        'Enter a new password': 'Enter a new password',
        'Something went wrong, please try again later': 'Something went wrong, please try again later',
        'username succesfully updated': 'username succesfully updated',
        'Username': 'Username',
        'Enter your username': 'Enter your username',
        'Choose your Language': 'Choose your Language',
        'Bitcoin public key': 'Bitcoin public key',
        'Root Address': 'Root Address',
        'Crypto Wallet': 'Crypto Wallet',
        'Application successfully created': 'Application successfully created',
        'Token refreshed': 'Token refreshed',
        'REFRESH': 'REFRESH',
        'API Integration': 'API Integration',
        'Application Name': 'Application Name',
        'Enter the name of your app': 'Enter the name of your app',
        'Account': 'Account'
    },
    'de': {
        'ID': 'ID',
        'Actions': 'Aktionen',
        'Hide': 'Verstecke',
        'Show the edition': 'Zeige die Edition',
        'Show all %d Editions': 'Zeige alle %d Editionen an',
        'by %s': 'von %s',
        'Account Settings': 'Kontoeinstellungen',
        'FAQ': 'Fragen & Antworten',
        'Terms of Service': 'AGB',
        'Log out': 'Log out',
        'Previous': 'Zurück',
        'Next': 'Weiter',
        '%s license': '%s license',
        'Log into': 'Log into',
        'Email': 'Email',
        'Enter your email': 'Enter your email',
        'Password': 'Password',
        'Enter your password': 'Enter your password',
        'Not an ascribe user': 'Not an ascribe user',
        'Sign up': 'Sign up',
        'Forgot my password': 'Forgot my password',
        'Rescue me': 'Rescue me',
        'LOGIN': 'LOGIN',
        'SIGNUP': 'SIGNUP',
        'Welcome to': 'Welcome to',
        'Sign up to ascribe': 'Sign up to ascribe',
        'Enter your password once again': 'Enter your password once again',
        'Enter a promocode here (Optional)': 'Enter a promocode here (Optional)',
        'I agree to the': 'I agree to the',
        'Confirm Password': 'Confirm Password',
        'Promocode': 'Promocode',
        'Sign up successful': 'Sign up successful',
        'We sent an email to your address': 'We sent an email to your address',
        'please confirm': 'please confirm',
        'Your password must be at least 10 characters': 'Your password must be at least 10 characters',
        'This password is securing your digital property like a bank account': 'This password is securing your digital property like a bank account',
        'Store it in a safe place': 'Store it in a safe place',
        'Reset the password for': 'Reset the password for',
        'Reset your ascribe password': 'Reset your ascribe password',
        'An email has been sent to': 'An email has been sent to',
        'Request successfully sent, check your email': 'Request successfully sent, check your email',
        'Reset your password': 'Reset your password',
        'Enter your email and we\'ll send a link': 'Enter your email and we\'ll send a link',
        'password successfully updated': 'password successfully updated',
        'Enter a new password': 'Enter a new password',
        'Something went wrong, please try again later': 'Something went wrong, please try again later',
        'username succesfully updated': 'username succesfully updated',
        'Username': 'Username',
        'Enter your username': 'Enter your username',
        'Choose your Language': 'Choose your Language',
        'Bitcoin public key': 'Bitcoin public key',
        'Root Address': 'Root Address',
        'Crypto Wallet': 'Crypto Wallet',
        'Application successfully created': 'Application successfully created',
        'Token refreshed': 'Token refreshed',
        'REFRESH': 'REFRESH',
        'API Integration': 'API Integration',
        'Application Name': 'Application Name',
        'Enter the name of your app': 'Enter the name of your app',
        'Account': 'Account'
    },
    'fr': {
        'ID': 'ID',
        'Actions': 'Actions',
        'Hide': 'Cacher',
        'Show the edition': 'Montrer l\'Édition',
        'Show all %d Editions': 'Montrer toutes les Éditions',
        'by %s': 'by %s',
        'Account Settings': 'Paramètres du compte',
        'FAQ': 'FAQ',
        'Terms of Service': 'Conditions d\'Utilisations',
        'Log out': 'Quitter',
        'Previous': 'Précédent',
        'Next': 'Suivant',
        '%s license': '%s license',
        'Log into': 'Se connecter à',
        'Email': 'E-mail',
        'Enter your email': 'Entrez votre e-mail',
        'Password': 'Mot de passe',
        'Enter your password': 'Entrez votre mot de passe',
        'Not an ascribe user': 'Pas un utilisateur d\'ascribe',
        'Sign up': 'Créer un compte',
        'Forgot my password': 'J\'ai oublié mon mot de passe',
        'Rescue me': 'Sauve-moi',
        'LOGIN': 'SE CONNECTER',
        'SIGNUP': 'CRÉER UN COMPTE',
        'Welcome to': 'Bienvenue chez',
        'Sign up to ascribe': 'S\'inscrire à ascribe',
        'Enter your password once again': 'Entrez votre mot de passe une fois de plus',
        'Enter a promocode here (Optional)': 'Entrez un code promotionnel ici (Facultatif)',
        'I agree to the': 'Je suis d\'accrod avec les',
        'Confirm Password': 'Confirmez le mot de passe',
        'Promocode': 'Code promotionnel',
        'Sign up successful': 'Inscription réussie',
        'We sent an email to your address': 'Nous avons envoyé un e-mail à votre adresse',
        'please confirm': 'veuillez confirmer',
        'Your password must be at least 10 characters': 'Votre mot de passe doit être composé d\'au moins 10 caractères',
        'This password is securing your digital property like a bank account': 'Ce mot de passe sécurise votre propriété numérique tel un compte bancaire',
        'Store it in a safe place': 'Conservez-le dans un endroit sécuritaire',
        'Reset the password for': 'Réinitialiser le mot de passe pour',
        'Reset your ascribe password': 'Réinitialiser votre mot de passe ascribe',
        'An email has been sent to': 'Un e-mail a été envoyé à',
        'Request successfully sent, check your email': 'Requête envoyée avec succès, veuillez consultez votre courrier électronique',
        'Reset your password': 'Réinitialiser votre mot de passe',
        'Enter your email and we\'ll send a link': 'Entrez votre e-mail et nous vous enverrons un lien',
        'password successfully updated': 'mise à jour du mot de passe réussie',
        'Enter a new password': 'Entrez un nouveau mot de passe',
        'Something went wrong, please try again later': 'Quelque chose ne fonctionne pas, veuillez réessayer plus tard',
        'username succesfully updated': 'nom d\'utilisateur mis à jour avec succès',
        'Username': 'Nom d\'utilisateur',
        'Enter your username': 'Entrez votre nom d\'utilisateur',
        'Choose your Language': 'Choisissez votre langue',
        'Bitcoin public key': 'Clé publique Bitcoin',
        'Root Address': 'Adresse Racine',
        'Crypto Wallet': 'Porte-monnaie Crypto',
        'Application successfully created': 'Application créée avec succès',
        'Token refreshed': 'Jeton rafraîchi',
        'REFRESH': 'RAFRAÎCHIR',
        'API Integration': 'Intégration de l\'API',
        'Application Name': 'Nom de l\'Application',
        'Enter the name of your app': 'Entrez le nom de votre application',
        'Account': 'Compte'
    }
};

export default languages;